---
- hosts: "{{ host }}"
  become: yes
  gather_facts: yes
  roles:
    - role: zabbix-agent-linux
      tags: [ zabbix-agent ]
    - role: docker_install
      tags: [ docker_install ]
    - role: zabbix-proxy-via-docker
      tags: [ zabbix-proxy ]
